## Gavin Trumbull
# assignment 8, eric matthes, 2nd edition, spring 2023
# CS150

In [2]:
import numpy as np

In [3]:
array1=np.arange(10,50,10)
aray=array1.reshape(2,2)
aray

array([[10, 20],
       [30, 40]])

In [4]:
print(aray**2)

[[ 100  400]
 [ 900 1600]]


In [5]:
print(aray+100)

[[110 120]
 [130 140]]


In [6]:
print(aray*5)

[[ 50 100]
 [150 200]]


In [7]:
print(aray**.5)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [12]:
array2=np.arange(3,30,3)
aray2=array2.reshape(3,3)
aray2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [11]:
array3=np.linspace(10,20,9)
aray3=array3.reshape(3,3)
aray3

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [13]:
aray2*aray3

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

In [19]:
p1=np.load('process1.npy')
print(p1)
p2=np.load('process2.npy')
print(p2)
p3=np.load('process3.npy')
print(p3)
p4=np.load('process4.npy')
print(p4)
p5=np.load('process5.npy')
print(p5)


[[52 12 81  0 58]]
[[96  4 61 16 43]]
[[38 96 45 17 58]]
[[97 21 22 25  6]]
[[77  6 19  2 74]]


In [23]:
array=np.concatenate([p1,p2,p3,p4,p5])
print(array)

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


In [29]:
print(array[:,:1].mean())
print(array[:,:2].mean())
print(array[:,:3].mean())
print(array[:,:4].mean())
print(array[:,:5].mean())

72.0
49.9
48.46666666666667
39.35
41.04
